###############################################################################
#Create date : 2022/5/29
#Last modify date : 2022/5/29
#Auther : ming
#Enviroment: Ubuntu-20.04.1 gcc 9.4.0 Intel(r) Core(TM) i5-10210U @ 1.60GHz
#Usage:
#	Makefile for SingleList
##############################################################################

.PHONY : main clean

main: main.c doubleList_im.c doubleList.h
	$(CC) -o main main.c doubleList_im.c

clean:
	rm -r main
